### ISSUE TITLE
Appreciation Note 

### ISSUE THREAD

**Issue by yesabhishek** [yasingencnet/webkit#1]
Hey Yasin!

Hope you're doing awesome!

I was on the look for some inspiration to jazz up my website (https://www.abhishekchoudhury.in/) when I stumbled upon your profile and found my way to this repository.

I haven't used too much GSAP yet, as I'm currently rocking TailwindCSS, Animate On Scroll and Sveltekit for my site. Your animations have got me excited to learn some new techniques and spruce up my site with some cool animations!

Thanks a bunch for keeping this template public—it's going to be very helpful for me and others looking to level up their websites.

Appreciate it big time! Have a fantastic evening ahead! :)

**Comment by yasingencnet** [comment]
Hello Abhishek,

Thanks for reaching out and for the kind words! I'm glad you found the animations inspiring. 

Cheers!
